export const CREATE_ANBUD = 'CREATE_ANBUD'
export const EDIT_ANBUD = 'EDIT_ANBUD'
export const DRAFT_ANBUD = 'DRAFT_ANBUD'
export const REPLACE_ANBUD = 'REPLACE_ANBUD'

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE'
export const REPLACE_EMPLOYEES = 'REPLACE_EMPLOYEES'
export const DRAFT_EMPLOYEE = 'DRAFT_EMPLOYEE'

export const REPLACE_CUSTOMERS = 'REPLACE_CUSTOMERS'
export const DRAFT_CUSTOMER = 'DRAFT_CUSTOMER'

export const REPLACE_UPPDRAG = 'REPLACE_UPPDRAG'
export const ADD_UPPDRAG = 'ADD_UPPDRAG'

export const REPLACE_DRAFTS = 'REPLACE_DRAFTS'